services:
  safia-website:
    build: .
    container_name: safia-website
    networks:
      - caddy
    restart: unless-stopped
    ports:
      - "3001:3001"
    labels:
      - "caddy=${DOMAIN}"
      - "caddy.reverse_proxy={{upstreams 80}}"

networks:
  caddy:
    external: true